### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Benmuiruri** [Benmuiruri/my-catalog#6]
Our Project has three people in it. 

1. Team member **One** [Selma Belhadj](https://github.com/selma-belhadj)
2. Team member **Two** [Ben Kiarie](https://github.com/Benmuiruri)
3. Team member **Three** [Linda](https://github.com/keza681)

The link to our Kanban Board is https://github.com/Benmuiruri/my-catalog/projects/1

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly assign a number of points for this task and add a more descriptive description for it.
![image](https://user-images.githubusercontent.com/24703171/175963323-4eb83a32-89a3-4d67-9191-a16611bda769.png)
- [ ] Kindly add a description for this task.
![image](https://user-images.githubusercontent.com/24703171/175963600-1a873987-ca0c-4ba0-b736-9f4e0f32a42a.png)


![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Benmuiruri** [comment]
Thanks for the review @gemmen29 we shall make the changes shortly.

**Comment by Benmuiruri** [comment]
Thanks for the review @dasileker
